### ISSUE TITLE
Chrome can not start downloading before I move the mouse

### ISSUE THREAD

**Issue by WangGuox1n** [JoMingyu/google-play-scraper#63] opened 2020-08-02 15:14 UTC
I use Chrome(on MacOS) to download the app, and Chrome can connect to the download website, but I have to move the mouse to active Chrome to start the download. Why?

**Comment by JoMingyu** [comment] 2020-08-08 02:19
Is this a valid issue? This project is just a scraping library.

**Comment by JoMingyu** [comment] 2020-08-11 06:23
I'll close this. If the issue is truly related to this project, reopen and tag me.

**Closed by JoMingyu** 2020-08-11 06:23 UTC
